name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore ASP.NET-Domain-Driven-Design-Template.sln

      - name: Build
        run: dotnet build ASP.NET-Domain-Driven-Design-Template.sln --no-restore --configuration Release
